# Generated by Django 4.0 on 2022-01-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField()),
                ('service_visited', models.CharField(max_length=100)),
                ('page_visited', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date_created', models.DateField()),
                ('date_updated', models.DateField()),
            ],
        ),
    ]
