# Generated by Django 4.0 on 2022-01-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
